name: "nichecompass_analysis"
description: Analysis based on the NicheCompass model
keywords:
  - spatial_atlas_building
  - niche_identification
  - niche_characterisation
  - cell-cell_communication_inference
  - spatial_reference_mapping
  - analysis
  - deep-learning
tools:
  - "nichecompass":
      description: "NicheCompass is a package for end-to-end analysis of spatial multiomics data by the Lotfollahi Lab"
      documentation: "https://nichecompass.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/Lotfollahi-lab/nichecompass"
      doi: "https://doi.org/10.1038/s41588-025-02120-6"
      licence: ["BSD-3-Clause license"]

input:
    - timestamp:
        type: value
        description: Timestamp (YYYYMMDD-HHMMSS)
    - - nichecompass_outdir:
          type: directory
          description: NicheCompass output directory
          pattern: "nichecompass_*"

output:
  notebook:
    - "notebook":
          type: file
          description: NicheCompass output jupyter notebook from papermill
          pattern: "*.ipynb"
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: "http://edamontology.org/format_3750" # YAML

authors:
  - "@ASUQ"
maintainers:
  - "@ASUQ"
