---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "imaging_tiledspotiflow"
description: run spotiflow on tiled data
keywords:
  - peak calling
  - image analysis
  - tiled data
  - spotiflow
tools:
  - "imaging":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence:
      identifier:

input:
  - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`

  - imgs:
      type: file
      description: raw images for segmentation
      pattern: "*.{ome.tif}"
        ontologies:
          - edam: "http://edamontology.org/format_3727"

  - bounding_box:
      type: int
      description: bounding box for each tile

  - channel_index:
      type: int
      description: channel index for peak calling


output:
  - bam:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`

    - "*.csv":
        type: file
        description: Peak locations
        pattern: "*.csv"
        ontologies:
          - edam: "http://edamontology.org/format_3752"

  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
