---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "anndatautils_toh5ad"
description: A module to convert AnnData convertable files to AnnData object and save it as .h5ad file
keywords:
  - anndata
  - h5ad
  - conversion

input:
  - - sample_id:
        type: string
        description: |
          Sample ID to be used as obs_names in the AnnData object
  - - input:
        type: [ "file" , "directory" ]
        description: |
          Input files to be converted to AnnData object. The first element of the tuple is the sample ID, and the second element is the file path.
  - - delimiter:
        type: string
        description: |
          Delimiter to be used to create obs_names in the format sample_id + delimiter + barcode

output:
  - output:
    - "*.h5ad":
        type: file
        description: .h5ad file containing the AnnData object
        pattern: "*.h5ad"


authors:
  - "@claptar"
maintainers:
  - "@claptar"
