---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "anndatautils_toh5ad"
description: A module to convert AnnData convertible files to AnnData object and save it as .h5ad file
keywords:
  - anndata
  - h5ad
  - conversion
tools:
  - anndata:
      description: |
        Anndata is a Python package for handling annotated data
        matrices in memory and on disk, positioned between pandas
        and xarray. anndata offers a broad range of computationally
        efficient features including, among others, sparse data support,
        lazy operations, and a PyTorch interface.
      homepage: https://anndata.readthedocs.io/en/stable/
      documentation: https://anndata.readthedocs.io/en/stable/
      doi: 10.21105/joss.04371
      license: BSD-3-Clause
  - scanpy:
      description: |
        Scanpy is a scalable toolkit for analyzing single-cell gene
        expression data built jointly with anndata. It includes preprocessing,
        visualization, clustering, trajectory inference and differential expression testing.
        The Python-based implementation efficiently deals with datasets of more than one million cells.
      homepage: https://scanpy.readthedocs.io/en/stable/
      documentation: https://scanpy.readthedocs.io/en/stable/
      doi: 10.1186/s13059-017-1382-0
      license: BSD-3-Clause

input:
  - - sample_id:
        type: string
        description: |
          Sample ID to be used as obs_names in the AnnData object
    - input:
        type: [ "file" , "directory" ]
        description: |
          Input files to be converted to AnnData object. The first element of the tuple is the sample ID, and the second element is the file path.
  - - delimiter:
        type: string
        description: |
          Delimiter to be used to create obs_names in the format sample_id + delimiter + barcode

output:
  - h5ad:
    - sample_id:
        type: string
        description: |
          Sample ID that was used as obs_names in the AnnData object
    - "*.h5ad":
        type: file
        description: .h5ad file containing the AnnData object
        pattern: "*.h5ad"
  - versions:
    - versions.yml:
        type: file
        description: |
          YML file containing the versions of the software used to create the AnnData object
        pattern: "versions.yml"


authors:
  - "@claptar"
maintainers:
  - "@claptar"
