# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "postcode_decoding"
description: Sort SAM/BAM/CRAM file
keywords:
  - spatial transcriptomics
  - decoding
  - postcode
  - probabilistic decoding
components:
  - imaging/postcodeprep
  - imaging/postcode
input:
  - ch_profile:
      type: file
      description: |
        The input channel containing the spot/cell profile files
        Structure: [ val(meta), path(profile) ]
      pattern: "*.npy"
  - ch_tabular_codebook:
      type: file
      description: |
        The codebook in a tabular format
        Structure: [ val(meta), path(tab_codebook) ]
      pattern: "*.{csv/tsv/xlsx}"
  - ch_readout_file:
      type: file
      description: |
        The input channel containing the readout file for MERFISH-like data
        Structure: [ val(meta), path(readout) ]
      pattern: "*.tsv"
  - ch_R:
      type: int
      description: |
        The number of imaging round for the profile
        Structure: [ val(meta), 6 ]
  - ch_loc:
      type: file
      description: |
        The cell/pixel/spot locatisable tsv file 
        Structure: [ val(meta), path(localisation) ]
      pattern: "*.{tsv/csv}"

output:
  - decoding_result:
      type: file
      description: |
        Channel containing decoded results
        Structure: [ val(meta), path(csv) ]
      pattern: "*.csv"
  - processed_profiles:
      type: file
      description: |
        Channel containing reformatted profile files
        Structure: [ val(meta), path(profile) ]
      pattern: "*.npy"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
