---
name: "ml_hematoxylineosin"

description:  A wrapper module for feature_hematoxylin_eosin_image_tiles.py script
keywords:
  - spatial-transcriptomics(xenium)
  - ml
  - feature-extraction
tools:
  - "ml":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: 
      identifier: 

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - harmonised_output:
        type: directory
        description: harmonised xenium output directory
  
 
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - "output_dir":
      type: directory
      description: Directory containing the hematoxylin eosin image tiles in zarr format.
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@dn10-sanger"
maintainers:
  - "@dn10-sanger"
